route:
  receiver: web.hook
  group_by:
  - alertname
  continue: false
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 5m
receivers:
- name: web.hook
  webhook_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    url: http://flask-app:5000
    max_alerts: 0
templates: []
