version: "3.4"

services:
  grpc-api:
    image: ghcr.io/deephaven/grpc-api:${VERSION:-latest} 
    expose:
      - '8080'
    volumes:
      - ./data:/data
      - api-cache:/cache
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx4g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/app.d

  web:
    image: ghcr.io/deephaven/web:${VERSION:-latest}
    expose:
      - '80'
    volumes:
      - ./data:/data
      - web-tmp:/tmp

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:${VERSION:-latest}
    environment:
      - BACKEND_ADDR=grpc-api:8080
    depends_on:
      - grpc-api
    expose:
      - '8080'

  envoy:
    image: ghcr.io/deephaven/envoy:${VERSION:-latest}
    depends_on:
      - web
      - grpc-proxy
      - grpc-api
    ports:
      - "10000:10000"

#  node_exporter:
#    image: quay.io/prometheus/node-exporter:latest
#    container_name: node_exporter
#    command:
#      - '--path.rootfs=/host'
#    pid: host
#    restart: unless-stopped
#    volumes:
#      - '/:/host:ro'
#    ports:
#      - 9100:9100

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

volumes:
    web-tmp:
    api-cache:
