version: "3.4"

services:
  redpanda:
      command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      image: docker.vectorized.io/vectorized/redpanda:v21.4.13
      ports:
      - 9092:9092
      - 29092:29092

  grpc-api:
    image: ghcr.io/deephaven/grpc-api:${VERSION:-latest}
    environment:
      JAVA_TOOL_OPTIONS: -Xmx6g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/data/app.d
    depends_on:
        - redpanda
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 6000M
        reservations:
          memory: 1000M
    expose:
      - '8080'
    volumes:
      - ./data:/data
      - api-cache:/cache

  web:
    image: ghcr.io/deephaven/web:${VERSION:-latest}
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g
    expose:
      - '80'
    volumes:
      - ./data:/data
      - web-tmp:/tmp

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:${VERSION:-latest}
    environment:
      - BACKEND_ADDR=grpc-api:8080
    depends_on:
      - grpc-api
    expose:
      - '8080'

  envoy:
    image: ghcr.io/deephaven/envoy:${VERSION:-latest}
    depends_on:
      - web
      - grpc-proxy
      - grpc-api
    ports:
      - "${PORT:-10000}:10000"

  registry:
    image: apicurio/apicurio-registry-mem:1.2.2.Final
    expose:
      - 8080
    ports:
      - "8081:8080"
    environment:
      QUARKUS_PROFILE: prod
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      APPLICATION_ID: registry_id
      APPLICATION_SERVER: localhost:9000

volumes:
    web-tmp:
    api-cache:
