route:
  receiver: web.hook
  group_by:
  - alertname
  continue: false
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 5m
receivers:
- name: web.hook
  webhook_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    url: http://7e6e-2603-6081-2300-1ee0-19e5-89f3-f316-8d4a.ngrok.io
    max_alerts: 0
templates: []
