name: Build CI

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ 'main' ]

jobs:  
  examples:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.3.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/examples
          labels: |
            org.opencontainers.image.vendor=Deephaven Data Labs
            org.opencontainers.image.title=Deephaven Examples
            org.opencontainers.image.description=Deephaven Examples
            org.opencontainers.image.licenses=Deephaven Community License Agreement 1.0
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./samples/
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
